[experiment]
name = "" # keep empty to prompt
mode = "piv" # droplet | film | piv
series_directory = "C:\CoughMachineData\260820_piv\step_1-5bar" # keep empty to prompt; set to "None" to disable saving data

[inputs.cough]
nr_runs = 3
multi_run_interval_s = 0
confirm_before_starting_next_run = false
record_droplet_size = false

[devices.cough_machine.inputs]
flow_curve_csv_path = ""
wait_before_run_ms = 0

[devices.cough_machine.inputs.nebuliser]
fill_time_s = 60
pressure_bar = 0.1

[devices.cough_machine.inputs.cleaning]
clean_pressure_bar = 5.0
valve_open_duration_s = 10
cycle_count = 1

[devices.cough_machine.inputs.tank]
pressure_bar = 1.5
settling_time_s = 120.0
avg_window_s = 10.0
tolerance_bar = 0.02
poll_interval_s = 0.2
intermediate_diff_bar = 0.1 # set together with intermediate_time_s (empty disables)
intermediate_time_s = 5 # set together with intermediate_diff_bar (empty disables)
