[experiment]
name = "" # keep empty to prompt
mode = "droplet" # droplet | film | piv
series_directory = "" # keep empty to prompt; set to "None" to disable saving data

[inputs.cough]
debug_mode = false
nr_runs = 5
multi_run_interval_s = 40
confirm_before_starting_next_run = false
record_droplet_size = true

[devices.cough_machine.inputs]
flow_curve_csv_path = "step300ms"
wait_before_run_ms = 59.5


[devices.cough_machine.inputs.tank]
pressure_bar = 1.5
settling_time_s = 60.0
avg_window_s = 5.0
tolerance_bar = 0.05
poll_interval_s = 0.2
intermediate_diff_bar = -0.1 # set together with intermediate_time_s (empty disables)
intermediate_time_s = 2 # set together with intermediate_diff_bar (empty disables)

[devices.pump.inputs]
syringe_volume_ml = 2.5
pump_rate_ml_per_min = 0.1
nr_droplets_to_skip_before_recording = 5

[devices.pump.infuse]
volume_ml = 6
rate_ml_min = 6

[devices.pump.withdraw]
volume_ml = 4.0
rate_ml_min = 5


[devices.vertical_stage.inputs]
tolerance_mm = 0.3
timeout_s = 30.0
poll_interval_s = 0.2

[devices.spraytec.inputs]
append_file_path = "C:/Users/Public/Documents/Malvern Instruments/Spraytec/Export Data/SPRAYTEC_APPEND_FILE.txt" # keep empty to trigger file dialog
tcm_trachea_bottom_z_mm = 326
tcm_trachea_height_mm = 15.15   
lift_zero_z_mm = 172.7 #lift actually at 1.3mm, so 174-1.3 =172.7
# TODO: Move this 1.3 somewhere it can be stored!
spraytec_to_lift_z_mm = 739  
table_height_mm = 920
tcm_trachea_exit_to_ref_x_mm = 44.5
tcm_trachea_exit_to_ref_y_mm = 200
spraytec_to_ref_x_mm = 44
spraytec_to_ref_y_mm = 483
stage_pos_x_zero_mm = 96
stage_pos_y_zero_mm = 655

[devices.spraytec.inputs.position]
spraytec_target_z_mm = "" # keep empty to prompt, or set target SprayTec z height in mm
stage_pos_x_mm = "" # keep empty to prompt
stage_pos_y_mm = "" # keep empty to prompt