[experiment]
name = "firmware_test_droplet"
mode = "droplet" # droplet | film | piv | manual
series_directory = "C:/CoughMachineData/260226_tests"

[inputs.core]
debug_mode = false
nr_runs = 3
multi_run_interval_s = 5.0
wait_before_run_ms = 67.5

[devices.cough_machine.inputs]
flow_curve_csv_path = "step"
tank_pressure_bar = 1.0
tank_pressure_settling_time_s = 60.0

[devices.pump.inputs]
syringe_volume_ml = 2.5
droplet_pump_rate_ml_per_min = 0.1
nr_droplets_to_skip_before_recording = 5

[devices.spraytec]
record_droplet_size = false

[devices.spraytec.inputs]
append_file_path = "" # keep empty to trigger file dialog
tcm_trachea_bottom_z_mm = 100.0
tcm_trachea_height_mm = 10.0
lift_zero_z_mm = 0.0
spraytec_to_lift_z_mm = 50.0
tcm_trachea_exit_to_ref_x_mm = 50.0
tcm_trachea_exit_to_ref_y_mm = 50.0
spraytec_to_ref_x_mm = 10.0
spraytec_to_ref_y_mm = 10.0
stage_pos_x_mm = "" # keep empty to prompt
stage_pos_y_mm = "" # keep empty to prompt